spring:
  datasource:
    url: jdbc:postgresql://ep-divine-haze-a5729o21-pooler.us-east-2.aws.neon.tech/food?sslmode=require
    username: neondb_owner
    password: npg_BIEe3MDv4smZ
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_schema: food
